version: "2.0"
services:
  ddd_casandra:
    image: "cassandra:latest"
    ports:
    - "7199:7199"
    - "7000:7000"
    - "7001:7001"
    - "9042:9042"
    - "9160:9160"
    volumes:
    - ./data/cassandra:/var/lib/cassandra